/*Read two numbers from user. Perform division operation and print the output. In the hidden testcase, the dividend is a valid number and the divisor is zero. 
In spite of divisor being zero, your code should not raise exception. How can you do that?*/

import java.util.*;
class Main{
    public static void main(String s[]){
        double a,b;
        Scanner ss=new Scanner(System.in);
        a=ss.nextDouble();
        b=ss.nextDouble();
    
            double c=a/b;
            System.out.println(c);
        
    }
}
